name: pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  node-pipeline:
    uses: harrydowning/github-workflows/.github/workflows/node-pipeline.yml@v1.0.0
    with:
      repository-owner: harrydowning
      check-run: | # shell
        set -x
        npm i
        npm run sort -- --check
        npm run format
        npm run lint
        npm run test
      release-run: | # shell
        set -x
        npm i
        npm run package
        npx vsce package
        npm run release
        npx vsce publish
